### PR TITLE
Second Repull

### PR DESCRIPTION
**Pull request by EnergyCrafter**

### CODE REVIEW

**Comment by sql-sith** [comment]
This reverse merge thing is still an accident waiting to happen. `git pull` (from the shell) is quicker, safer, and (this is important) _expected_. Can you show me places on the Internet where people are recommending this instead of the extremely simple and reliable `git pull`?

**Comment by EnergyCrafter** [comment]
Since I am not using a local copy of the master branch, this seems to be the only way I can keep my branch up-to-date.  And it seems that there isn't any documentation on the internet-side of github, only stuff dealing with the shell (which I don't use).  That is my crazy reasoning on the reverse merge. :-)

**Comment by sql-sith** [comment]
Thanks, Isaac. I'm going to check with a guy who is a true GitHub expert and see what he thinks. It's not the merging to your branch that bothers me - it's what happens if I merge back to master. It seems like it should work and be safe (in which case I would need to rescind the "accident waiting to happen" part). I probably should have anticipated that some people (maybe everybody) would only use GitHub and not git if I didn't show them how. We really should have had you pull forks to your own repositories (for you, it would put a copy of cdc2017-summer under EnergyCrafter) and then you guys could work there until you wanted to do a pull request back to master. Next time I'll know to be more thoughtful about how I want students to use git and GitHub, so ... it's all good.

**Comment by sql-sith** [comment]
As far as documentation, there are these little guides for GitHub: https://guides.github.com/ . They do assume that you'll want to code on your own computer, and to do that you'll at least want to use the GitHub for Windows application.

There are also "bootcamp" topics on https://help.github.com/ . They also assume you will be using git ... but if you are using GitHub, you already are using git, really, since GitHub features are a superset of git features.

**Comment by sql-sith** [comment]
Anyway, sorry I get nervous about this. I need to remember, it's not like this is GoDaddy's codebase or something.  :)   I'll ask my friend about this - he'll definitely help me understand if there are any risks of merging a reverse merge back to master.

**Pull request merged**
